<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Technician;
use Illuminate\Support\Facades\Hash;

class TechnicianSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $technicians = [
            [
                'user' => [
                    'name' => 'Dr. Sarah Ahmed',
                    'mobile' => '+923001234570',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Sarah Ahmed',
                    'father_name' => 'Ahmad Ali',
                    'cnic' => '12345-1234567-1',
                    'date_of_birth' => '1988-05-12',
                    'home_address' => '123 Main Street, Lahore, Pakistan',
                    'clinic_address' => '456 Veterinary Clinic, Model Town, Lahore',
                    'province' => 'Punjab',
                    'district' => 'Lahore',
                    'tehsil' => 'Lahore',
                    'city' => 'Lahore',
                    'degree_year' => '2010',
                    'cnic_front_image' => 'cnic_front_sarah.jpg',
                    'cnic_back_image' => 'cnic_back_sarah.jpg',
                    'degree_front_image' => 'degree_front_sarah.jpg',
                    'degree_back_image' => 'degree_back_sarah.jpg',
                    'years_of_experience' => 14,
                    'customers_per_month' => 25,
                    'areas_of_expertise' => 'Artificial Insemination, Reproductive Health, Dairy Management',
                    'mobile_1' => '+923001234570',
                    'mobile_2' => '+923001234571',
                    'clinic_latitude' => '31.5204',
                    'clinic_longitude' => '74.3587',
                    'unique_code' => 'TECH001',
                    'status' => 'active',
                    'availability' => 'online',
                    'admin_comments' => 'Excellent performance, highly recommended for AI services.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Muhammad Hassan',
                    'mobile' => '+923001234572',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Muhammad Hassan',
                    'father_name' => 'Ali Hassan',
                    'cnic' => '12345-1234567-2',
                    'date_of_birth' => '1985-09-18',
                    'home_address' => '789 Park Avenue, Karachi, Pakistan',
                    'clinic_address' => '321 Animal Health Center, Clifton, Karachi',
                    'province' => 'Sindh',
                    'district' => 'Karachi',
                    'tehsil' => 'Clifton',
                    'city' => 'Karachi',
                    'degree_year' => '2008',
                    'cnic_front_image' => 'cnic_front_hassan.jpg',
                    'cnic_back_image' => 'cnic_back_hassan.jpg',
                    'degree_front_image' => 'degree_front_hassan.jpg',
                    'degree_back_image' => 'degree_back_hassan.jpg',
                    'years_of_experience' => 16,
                    'customers_per_month' => 30,
                    'areas_of_expertise' => 'Bovine Reproduction, Semen Analysis, Farm Management',
                    'mobile_1' => '+923001234572',
                    'mobile_2' => '+923001234573',
                    'clinic_latitude' => '24.8607',
                    'clinic_longitude' => '67.0011',
                    'unique_code' => 'TECH002',
                    'status' => 'active',
                    'availability' => 'online',
                    'admin_comments' => 'Senior technician with extensive experience in bovine reproduction.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Ayesha Malik',
                    'mobile' => '+923001234574',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Ayesha Malik',
                    'father_name' => 'Malik Ahmed',
                    'cnic' => '12345-1234567-3',
                    'date_of_birth' => '1992-12-03',
                    'home_address' => '456 Garden Street, Islamabad, Pakistan',
                    'clinic_address' => '789 Veterinary Services, F-8, Islamabad',
                    'province' => 'Islamabad Capital Territory',
                    'district' => 'Islamabad',
                    'tehsil' => 'Islamabad',
                    'city' => 'Islamabad',
                    'degree_year' => '2015',
                    'cnic_front_image' => 'cnic_front_ayesha.jpg',
                    'cnic_back_image' => 'cnic_back_ayesha.jpg',
                    'degree_front_image' => 'degree_front_ayesha.jpg',
                    'degree_back_image' => 'degree_back_ayesha.jpg',
                    'years_of_experience' => 9,
                    'customers_per_month' => 20,
                    'areas_of_expertise' => 'Reproductive Technology, Animal Welfare, Health Management',
                    'mobile_1' => '+923001234574',
                    'mobile_2' => null,
                    'clinic_latitude' => '33.6844',
                    'clinic_longitude' => '73.0479',
                    'unique_code' => 'TECH003',
                    'status' => 'active',
                    'availability' => 'offline',
                    'admin_comments' => 'Good performance in reproductive technology services.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Ahmed Raza',
                    'mobile' => '+923001234575',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Ahmed Raza',
                    'father_name' => 'Raza Ali',
                    'cnic' => '12345-1234567-4',
                    'date_of_birth' => '1980-04-25',
                    'home_address' => '321 Farm Road, Faisalabad, Pakistan',
                    'clinic_address' => '654 Livestock Center, Jaranwala, Faisalabad',
                    'province' => 'Punjab',
                    'district' => 'Faisalabad',
                    'tehsil' => 'Jaranwala',
                    'city' => 'Faisalabad',
                    'degree_year' => '2005',
                    'cnic_front_image' => 'cnic_front_ahmed.jpg',
                    'cnic_back_image' => 'cnic_back_ahmed.jpg',
                    'degree_front_image' => 'degree_front_ahmed.jpg',
                    'degree_back_image' => 'degree_back_ahmed.jpg',
                    'years_of_experience' => 19,
                    'customers_per_month' => 35,
                    'areas_of_expertise' => 'Large Animal Medicine, Reproductive Health, Farm Consultation',
                    'mobile_1' => '+923001234575',
                    'mobile_2' => '+923001234576',
                    'clinic_latitude' => '31.4504',
                    'clinic_longitude' => '73.1350',
                    'unique_code' => 'TECH004',
                    'status' => 'pending',
                    'availability' => 'offline',
                    'admin_comments' => 'Application under review. Documents submitted.',
                    'admin_signature' => null,
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Fatima Khan',
                    'mobile' => '+923001234577',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Fatima Khan',
                    'father_name' => 'Khan Muhammad',
                    'cnic' => '12345-1234567-5',
                    'date_of_birth' => '1990-08-15',
                    'home_address' => '567 University Road, Peshawar, Pakistan',
                    'clinic_address' => '890 Animal Care Center, Hayatabad, Peshawar',
                    'province' => 'Khyber Pakhtunkhwa',
                    'district' => 'Peshawar',
                    'tehsil' => 'Peshawar',
                    'city' => 'Peshawar',
                    'degree_year' => '2013',
                    'cnic_front_image' => 'cnic_front_fatima.jpg',
                    'cnic_back_image' => 'cnic_back_fatima.jpg',
                    'degree_front_image' => 'degree_front_fatima.jpg',
                    'degree_back_image' => 'degree_back_fatima.jpg',
                    'years_of_experience' => 11,
                    'customers_per_month' => 22,
                    'areas_of_expertise' => 'Small Animal Medicine, Reproductive Health, Vaccination',
                    'mobile_1' => '+923001234577',
                    'mobile_2' => '+923001234578',
                    'clinic_latitude' => '34.0151',
                    'clinic_longitude' => '71.5249',
                    'unique_code' => 'TECH005',
                    'status' => 'active',
                    'availability' => 'online',
                    'admin_comments' => 'Specialized in small animal reproductive services.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Usman Ali',
                    'mobile' => '+923001234579',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Usman Ali',
                    'father_name' => 'Ali Akbar',
                    'cnic' => '12345-1234567-6',
                    'date_of_birth' => '1987-11-22',
                    'home_address' => '234 Industrial Area, Multan, Pakistan',
                    'clinic_address' => '456 Livestock Services, Bosan Road, Multan',
                    'province' => 'Punjab',
                    'district' => 'Multan',
                    'tehsil' => 'Multan',
                    'city' => 'Multan',
                    'degree_year' => '2011',
                    'cnic_front_image' => 'cnic_front_usman.jpg',
                    'cnic_back_image' => 'cnic_back_usman.jpg',
                    'degree_front_image' => 'degree_front_usman.jpg',
                    'degree_back_image' => 'degree_back_usman.jpg',
                    'years_of_experience' => 13,
                    'customers_per_month' => 28,
                    'areas_of_expertise' => 'Bovine AI, Semen Collection, Farm Management',
                    'mobile_1' => '+923001234579',
                    'mobile_2' => '+923001234580',
                    'clinic_latitude' => '30.1575',
                    'clinic_longitude' => '71.5249',
                    'unique_code' => 'TECH006',
                    'status' => 'active',
                    'availability' => 'offline',
                    'admin_comments' => 'Experienced in large-scale farm operations.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Zainab Sheikh',
                    'mobile' => '+923001234581',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Zainab Sheikh',
                    'father_name' => 'Sheikh Ahmad',
                    'cnic' => '12345-1234567-7',
                    'date_of_birth' => '1995-03-10',
                    'home_address' => '345 Model Town, Rawalpindi, Pakistan',
                    'clinic_address' => '678 Veterinary Clinic, Saddar, Rawalpindi',
                    'province' => 'Punjab',
                    'district' => 'Rawalpindi',
                    'tehsil' => 'Rawalpindi',
                    'city' => 'Rawalpindi',
                    'degree_year' => '2018',
                    'cnic_front_image' => 'cnic_front_zainab.jpg',
                    'cnic_back_image' => 'cnic_back_zainab.jpg',
                    'degree_front_image' => 'degree_front_zainab.jpg',
                    'degree_back_image' => 'degree_back_zainab.jpg',
                    'years_of_experience' => 6,
                    'customers_per_month' => 15,
                    'areas_of_expertise' => 'Reproductive Technology, Animal Health, Modern AI Techniques',
                    'mobile_1' => '+923001234581',
                    'mobile_2' => null,
                    'clinic_latitude' => '33.5651',
                    'clinic_longitude' => '73.0169',
                    'unique_code' => 'TECH007',
                    'status' => 'active',
                    'availability' => 'online',
                    'admin_comments' => 'Young and enthusiastic, good with modern techniques.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Imran Shah',
                    'mobile' => '+923001234582',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Imran Shah',
                    'father_name' => 'Shah Muhammad',
                    'cnic' => '12345-1234567-8',
                    'date_of_birth' => '1983-07-08',
                    'home_address' => '456 Canal Road, Sialkot, Pakistan',
                    'clinic_address' => '789 Animal Health Services, Cantt, Sialkot',
                    'province' => 'Punjab',
                    'district' => 'Sialkot',
                    'tehsil' => 'Sialkot',
                    'city' => 'Sialkot',
                    'degree_year' => '2007',
                    'cnic_front_image' => 'cnic_front_imran.jpg',
                    'cnic_back_image' => 'cnic_back_imran.jpg',
                    'degree_front_image' => 'degree_front_imran.jpg',
                    'degree_back_image' => 'degree_back_imran.jpg',
                    'years_of_experience' => 17,
                    'customers_per_month' => 32,
                    'areas_of_expertise' => 'Large Animal Medicine, Reproductive Health, Emergency Care',
                    'mobile_1' => '+923001234582',
                    'mobile_2' => '+923001234583',
                    'clinic_latitude' => '32.4945',
                    'clinic_longitude' => '74.5229',
                    'unique_code' => 'TECH008',
                    'status' => 'active',
                    'availability' => 'online',
                    'admin_comments' => 'Senior technician with excellent emergency response record.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Saima Riaz',
                    'mobile' => '+923001234584',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Saima Riaz',
                    'father_name' => 'Riaz Ahmed',
                    'cnic' => '12345-1234567-9',
                    'date_of_birth' => '1989-12-30',
                    'home_address' => '678 Gulberg, Gujranwala, Pakistan',
                    'clinic_address' => '123 Veterinary Center, Model Town, Gujranwala',
                    'province' => 'Punjab',
                    'district' => 'Gujranwala',
                    'tehsil' => 'Gujranwala',
                    'city' => 'Gujranwala',
                    'degree_year' => '2012',
                    'cnic_front_image' => 'cnic_front_saima.jpg',
                    'cnic_back_image' => 'cnic_back_saima.jpg',
                    'degree_front_image' => 'degree_front_saima.jpg',
                    'degree_back_image' => 'degree_back_saima.jpg',
                    'years_of_experience' => 12,
                    'customers_per_month' => 26,
                    'areas_of_expertise' => 'Dairy Management, Reproductive Health, Nutrition Counseling',
                    'mobile_1' => '+923001234584',
                    'mobile_2' => '+923001234585',
                    'clinic_latitude' => '32.1877',
                    'clinic_longitude' => '74.1945',
                    'unique_code' => 'TECH009',
                    'status' => 'pending',
                    'availability' => 'offline',
                    'admin_comments' => 'Application pending document verification.',
                    'admin_signature' => null,
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Nadeem Qureshi',
                    'mobile' => '+923001234586',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Nadeem Qureshi',
                    'father_name' => 'Qureshi Ali',
                    'cnic' => '12345-1234567-0',
                    'date_of_birth' => '1986-06-14',
                    'home_address' => '789 Satellite Town, Quetta, Pakistan',
                    'clinic_address' => '456 Animal Care Clinic, Jinnah Road, Quetta',
                    'province' => 'Balochistan',
                    'district' => 'Quetta',
                    'tehsil' => 'Quetta',
                    'city' => 'Quetta',
                    'degree_year' => '2009',
                    'cnic_front_image' => 'cnic_front_nadeem.jpg',
                    'cnic_back_image' => 'cnic_back_nadeem.jpg',
                    'degree_front_image' => 'degree_front_nadeem.jpg',
                    'degree_back_image' => 'degree_back_nadeem.jpg',
                    'years_of_experience' => 15,
                    'customers_per_month' => 24,
                    'areas_of_expertise' => 'Livestock Health, Reproductive Services, Disease Prevention',
                    'mobile_1' => '+923001234586',
                    'mobile_2' => '+923001234587',
                    'clinic_latitude' => '30.1798',
                    'clinic_longitude' => '71.4920',
                    'unique_code' => 'TECH010',
                    'status' => 'active',
                    'availability' => 'offline',
                    'admin_comments' => 'Specialized in livestock health and disease prevention.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Hina Aslam',
                    'mobile' => '+923001234588',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Hina Aslam',
                    'father_name' => 'Aslam Khan',
                    'cnic' => '12345-1234568-1',
                    'date_of_birth' => '1993-09-25',
                    'home_address' => '234 Defense Housing, Lahore, Pakistan',
                    'clinic_address' => '567 Modern Veterinary Services, DHA, Lahore',
                    'province' => 'Punjab',
                    'district' => 'Lahore',
                    'tehsil' => 'Lahore',
                    'city' => 'Lahore',
                    'degree_year' => '2016',
                    'cnic_front_image' => 'cnic_front_hina.jpg',
                    'cnic_back_image' => 'cnic_back_hina.jpg',
                    'degree_front_image' => 'degree_front_hina.jpg',
                    'degree_back_image' => 'degree_back_hina.jpg',
                    'years_of_experience' => 8,
                    'customers_per_month' => 18,
                    'areas_of_expertise' => 'Pet Care, Reproductive Health, Modern Veterinary Techniques',
                    'mobile_1' => '+923001234588',
                    'mobile_2' => null,
                    'clinic_latitude' => '31.5204',
                    'clinic_longitude' => '74.3587',
                    'unique_code' => 'TECH011',
                    'status' => 'active',
                    'availability' => 'online',
                    'admin_comments' => 'Good with modern veterinary techniques and pet care.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
            [
                'user' => [
                    'name' => 'Dr. Tariq Mahmood',
                    'mobile' => '+923001234589',
                    'role' => 'technician',
                    'password' => Hash::make('password123'),
                ],
                'technician' => [
                    'name' => 'Dr. Tariq Mahmood',
                    'father_name' => 'Mahmood Ali',
                    'cnic' => '12345-1234568-2',
                    'date_of_birth' => '1981-01-18',
                    'home_address' => '345 Old City, Hyderabad, Pakistan',
                    'clinic_address' => '678 Livestock Health Center, Latifabad, Hyderabad',
                    'province' => 'Sindh',
                    'district' => 'Hyderabad',
                    'tehsil' => 'Hyderabad',
                    'city' => 'Hyderabad',
                    'degree_year' => '2006',
                    'cnic_front_image' => 'cnic_front_tariq.jpg',
                    'cnic_back_image' => 'cnic_back_tariq.jpg',
                    'degree_front_image' => 'degree_front_tariq.jpg',
                    'degree_back_image' => 'degree_back_tariq.jpg',
                    'years_of_experience' => 18,
                    'customers_per_month' => 40,
                    'areas_of_expertise' => 'Large Animal Surgery, Reproductive Health, Farm Consultation',
                    'mobile_1' => '+923001234589',
                    'mobile_2' => '+923001234590',
                    'clinic_latitude' => '25.3960',
                    'clinic_longitude' => '68.3578',
                    'unique_code' => 'TECH012',
                    'status' => 'active',
                    'availability' => 'online',
                    'admin_comments' => 'Highly experienced in large animal surgery and consultation.',
                    'admin_signature' => 'Admin Signature',
                ],
            ],
        ];

        foreach ($technicians as $technicianData) {
            // Create user
            $user = User::create($technicianData['user']);
            
            // Create technician profile
            Technician::create(array_merge($technicianData['technician'], ['user_id' => $user->id]));
        }
    }
}